version: '3.7'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    ports:
      - "8002:8000"

  service:
    build:
      context: ..
      dockerfile: crosssite/Dockerfile-service
    volumes:
      - ../service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh

networks:
  envoymesh: {}
